source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'NovaliaBLE_Example' do
  pod "NovaliaBLE", :path => "../"
end

target 'NovaliaBLE_Tests' do
  pod "NovaliaBLE", :path => "../"

  
end
